[build]
publish = "public"
command = "npm run project-setup && npm run build"

[build.environment]
HUGO_VERSION = "0.121.2"
GO_VERSION = "1.20.5"
NODE_VERSION = "18"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
